playjoom_backup:
    resource: "@PlayjoomBackupBundle/Controller/"
    type:     annotation
    prefix:   /

playjoom_update:
    resource: "@PlayjoomUpdateBundle/Controller/"
    type:     annotation
    prefix:   /

playjoom_install:
    resource: "@PlayjoomInstallBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
